/**
 * 功能：动作名称
 * 作者：安超
 * 日期： 2018/3/19
 */

export const SET_DATASOURCE_LIST_ORIGIN_TABLE = 'SET_DATASOURCE_LIST_ORIGIN_TABLE'
export const MODIFY_DATASOURCE_LIST_ORIGIN_TABLE = 'MODIFY_DATASOURCE_LIST_ORIGIN_TABLE'
export const SET_DATASOURCE_LIST_HEADERS_ORIGIN_TABLE = 'SET_DATASOURCE_LIST_HEADERS_ORIGIN_TABLE'

export const SET_ORIGINNAL_LIST_ORIGIN_TABLE = 'SET_ORIGINNAL_LIST_ORIGIN_TABLE'
export const SET_ORIGIN_LIST_HEADERS_ORIGIN_TABLE = 'SET_ORIGIN_LIST_HEADERS_ORIGIN_TABLE'
export const MODIFY_ORIGIN_LIST_ORIGIN_TABLE = 'MODIFY_ORIGIN_LIST_ORIGIN_TABLE'

export const SET_ORIGINNAL_FIELD_ORIGIN_TABLE = 'SET_ORIGINNAL_FIELD_ORIGIN_TABLE'
export const SET_ORIGIN_FIELD_HEADERS_ORIGIN_TABLE = 'SET_ORIGIN_FIELD_HEADERS_ORIGIN_TABLE'
export const MODIFY_ORIGIN_FIELD_ORIGIN_TABLE = 'MODIFY_ORIGIN_FIELD_ORIGIN_TABLE'
