/**
 * 功能：公共动作
 * 作者：安超
 * 日期：2018/8/18
 */

export const SET_USERTIMESTAMP_PUBLIC = 'SET_USERTIMESTAMP_PUBLIC'
export const USERTIMESTAMP_CHANGE_PUBLIC = 'USERTIMESTAMP_CHANGE_PUBLIC'


// 规则添加
export const SET_OUTPUT_CANDIDATES_RULE_CONFIG = 'SET_OUTPUT_CANDIDATES_RULE_CONFIG'
export const SET_RULE_CLASSES_RULE_CONFIG = 'SET_RULE_CLASSES_RULE_CONFIG'
export const GET_RULE_INPUT_OPTIONS_RULE_CONFIG = 'GET_RULE_INPUT_OPTIONS_RULE_CONFIG'
export const ADD_RULE_RULE_CONFIG = 'ADD_RULE_RULE_CONFIG'
export const SET_EDIT_RULE_CONFIG = 'SET_EDIT_RULE_CONFIG'
export const CHANGE_FIRST_RULE_SEL_RULE_CONFIG = 'CHANGE_FIRST_RULE_SEL_RULE_CONFIG'
export const CHANGE_SECOND_RULE_SEL_RULE_CONFIG = 'CHANGE_SECOND_RULE_SEL_RULE_CONFIG'
export const SET_EDIT_FLAG_RULE_CONFIG = 'SET_EDIT_FLAG_RULE_CONFIG'
export const RESET_ADD_RULE_CONFIG = 'RESET_ADD_RULE_CONFIG'
